name: Lint & Format (Ruff) - Auto-Fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ruff-auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run ruff format and fix
        run: |
          ruff format . || true
          ruff check . --fix || true
      - name: Commit & push fixes
        run: |
          git config user.name "ticatwolves"
          git config user.email "ticatwolves@gmail.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "style: ruff autoformat"
            git push
          else
            echo "No formatting changes"
          fi
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
