name: Tests (pytest)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pytest-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Determine event context
        id: event
        run: |
          echo "EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV
          echo "PR_MERGED=${{ github.event.pull_request.merged }}" >> $GITHUB_ENV || true
      - name: Checkout merge commit for PR closed event
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Checkout for push to main
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt || true
          pip install pytest

      - name: Run tests
        run: |
          pytest -q